### ISSUE TITLE
recommended hardware

### ISSUE THREAD

**Issue by axelreichwein** [MichSchli/RelationPrediction#2]
I ran the relational prediction training on my PC without GPU using the toy dataset and it is still running after 12+h hours. Is there any specific hardware configuration using GPU which you can recommend?

**Comment by weiying98** [comment]
"The configuration file (gcn_basis) is set to compute gradients over batches of 30.000 edges (GraphBatchSize). We use a naive sampling algorithm (found in train.py) which only stops when 30.000 unique edges have been sampled. Set GraphBatchSize to something < 43 (or delete the row with the setting, to avoid subsampling entirely), and you should have no problems running on the toy dataset." 

I'd emailed Michael and this was the reply he gave.

**Comment by axelreichwein** [comment]
Thank you @weiying98 ! Very helpful!
